NUMERO_COMPANEROS_REQUERIDOS = 9
TIEMPO_REACCION_SEGUNDOS = 120
PERMITIR_RECICLAJE = False
FALTAS_MAXIMAS = 3

BANEO_INACTIVIDAD_DIAS = 3
DURACION_BANEO = 7
REPETICION_INACTIVIDAD_EXPULSION = True
PRORROGA_MAXIMA_DIAS = 7
