# /mensajes/viral_texto.py

MENSAJE_FIJO = (
    "🧵 **¡Bienvenido a GO-VIRAL!**\n\n"
    "Este es el canal donde *todos nos apoyamos* para viralizar nuestro contenido en 𝕏 (Twitter).\n\n"
    "**Lee estas reglas y síguelas al pie de la letra para participar:**\n"
    "—\n"
    "1️⃣ **Formato correcto de publicación:**\n"
    "* Solo se permite el enlace limpio de tu tweet:\n"
    "  `https://x.com/usuario/status/1234567890`\n"
    "* El bot corregirá automáticamente los enlaces mal formateados, simulando que fuiste tú quien publicó.\n"
    "  (Recibirás un aviso educativo de 15 segundos y un DM explicándote el error).\n\n"
    "2️⃣ **Valida tu publicación:**\n"
    "* Reacciona con 👍 a tu propio post *en los primeros 2 minutos*.\n"
    "* Si no reaccionas a tiempo, el bot eliminará tu mensaje automáticamente.\n\n"
    "3️⃣ **Apoya antes de publicar de nuevo:**\n"
    "* Debes dar **apoyo genuino** (🔥 RT + Like + Comentario) a los **9 compañeros anteriores** antes de volver a publicar.\n"
    "* Si hay menos de 9 publicaciones, apoya a todas las disponibles.\n\n"
    "4️⃣ **Intervalo entre publicaciones:**\n"
    "* Espera al menos **2 publicaciones válidas** de otros miembros antes de volver a publicar.\n"
    "* Si solo hay 2 publicaciones después de la tuya (y ya las apoyaste), puedes volver a publicar aunque haya pasado 1 día.\n\n"
    "5️⃣ **Importante:**\n"
    "* No uses 🔥 en tu propio post.\n"
    "* No recicles hilos sin permiso.\n"
    "* No borres tus publicaciones después de publicarlas aquí.\n\n"
    "6️⃣ **Consecuencias y faltas:**\n"
    "* 1ª falta: Aviso por DM.\n"
    "* 2ª falta: Bloqueo 24h.\n"
    "* 3ª falta: Bloqueo 1 semana (luego reinicia el ciclo).\n"
    "* El sistema es automático y justo.\n"
    "—\n"
    "🧩 **¿Dudas o problemas?**\n"
    "* Lee las reglas completas en `#✅normas-generales`.\n"
    "* Pregunta siempre en `#👨🔧soporte` antes de molestar a los moderadores.\n\n"
    "🔥 **Aquí se viene a crecer. El que apoya, crece. El que aprende, nunca se queda atrás.**\n"
    "—\n"
    "![Logo](https://drive.google.com/uc?export=view&id=1KQTwE3IazBixpiF5vHa3eSTZoKYZUNd9)\n"
    "*Mensaje automatizado por VXbot — actualizado al {fecha}*"
)

MENSAJE_BIENVENIDA_NUEVO = (
    "🎉 **¡Bienvenido/a a tu primera publicación en GO-VIRAL!**\n\n"
    "👏 Te acabas de unir al sistema de apoyo viral de la comunidad. Aquí, cada publicación cuenta y cada miembro suma.\n\n"
    "**¿Qué debes saber a partir de ahora?**\n"
    "* **Recuerda apoyar con 🔥 (RT + LIKE + Comentario) a los 9 compañeros anteriores antes de tu próxima publicación.**\n"
    "* **Siempre reacciona con 👍 a tus propios posts en los primeros 2 minutos.**\n"
    "* **Entre cada publicación tuya, espera que al menos 2 personas publiquen después.**\n"
    "* Usa solo enlaces limpios como este:\n"
    "  `https://x.com/usuario/status/1234567890`\n\n"
    "🤖 *El bot automatizará todo el proceso, te avisará si algo no está bien y te ayudará a aprender cada paso.*\n"
    "🔗 Si tienes dudas, lee las reglas en `#✅normas-generales` o pregunta en `#👨🔧soporte`.\n"
    "—\n"
    "¡Gracias por ser parte del crecimiento colectivo!\n"
    "![Logo](https://drive.google.com/uc?export=view&id=1KQTwE3IazBixpiF5vHa3eSTZoKYZUNd9)\n"
    "*Mensaje automatizado por VXbot*"
)
